### ISSUE TITLE
Activation Options for activationController class

### ISSUE THREAD

**Issue by newwby** [newwby/ddat-gpf.entities#12]
<details><summary>(original note dump here)</summary>
<p>
_**notes dump from script todos**_

```
#//TODO
#	event on every frame (_process Input.pressed) instead of on input
#	add activate at minimum hold option (rather than on release after)
```
</p>
</details> 

- [x] **ACTIVATION.INPUT_WHILST_HELD**
activates every frame whilst input is held

- [x] **ACTIVATION.HOLD_MINIMUM**
as 'activation.confirmed_hold' but automatically activates when the minimum hold duration is reached

- [x] change ACTIVATION.INPUT_ACTIVATED to ACTIVATION.PRESSED for consistency

**Comment by newwby** [comment]
ACTIVATION.HOLD_MINIMUM done as of 408e0dd

**Comment by newwby** [comment]
HOLD_MINIMUM done as of 408e0dd
