### ISSUE TITLE
base structure for the nodePool class

### ISSUE THREAD

**Issue by newwby** [newwby/ddat-gpf.entities#19]
<details><summary><b>Original Notes</b></summary>
<p>

```

#//TODO
# method to set default properties
# method to change active/inactive state (and force properties)
# method to remove an object from the objectPool
# method to spawn by instancing
# spawn method arguments that can override forced/default properties

# older notes
# behaviour
# on instance:
#	which signals determine an object turning inactive or active
#	connect correct signals to the pool
#	which properties should be set/unset when the object turns inactive 

```

</p>
</details> 

### **Design Goals**

- an objectPool is separate to an entitySpawner (though the latter may be extended from it?)
- an objectPool is created and managed by globalPool
- an objectPool creates and manages objects
- an objectPool does not delete unwanted objects but sets them unused/disabled
- an objectPool reuses unwanted objects instead of creating new ones
- an objectPool can automatically set properties on new objects

### **Development Goals**

**must-haves**
- [x] object can be manually added to the pool
- [x] object can be manually removed from the pool
- [x] objects can be created and added to the pool
- [x] objects can be made active within the pool
- [x] objects can be made inactive within the pool
- [x] get_object method
- [x] get_next_inactive_object method

**property register behaviour**
- [x] property register force property setting (_set_object_properties method)
- [x] property register setting for initial
- [x] property register setting for active
- [x] property register setting for inactive

**automatical active/inactive signal management**
- [ ] automatic connection of signals to change active state
- [ ] managed removal of active-state signals if object leaves pool
- [ ] managed addition of active-state signals if object manually added to pool

**nice-to-haves**
- [x] prevent changing target scene after init
- [x] disabling objectPool if target scene is invalid
- [x] function of minimum_pool_size property

**known bugs**
- [x] re-enable and fix **_check_pool_minimum_size** method
- [x] (post #22) should extend node2D not node
else cannot use positional spawn arguments as replacement for entitySpawner

**Comment by newwby** [comment]
(notes taken from 67b8c33)

**Comment by newwby** [comment]
consolidated original activate/deactivate methods in 045094f but added public versions for manual management as option 3f3e0b9

**Comment by newwby** [comment]
finished off some other methods with: 5ee026c, bd680e4, and 1fd287f

**Comment by newwby** [comment]
moved some tasks to #27 to highlight the essential remaining tasks versus the out-of-scope or remaining nice-to-have tasks
